@host = http://localhost:9080/simple-notes/api
@threadId = a97c3ee1-d399-4b13-a72a-f24458d590a1
@noteId = a99c3ee1-d399-4b13-a72a-f24458d590a1
@newThreadId = b12c3ee1-d399-4b13-a72a-f24458d590b1
@newNoteId = a99c3ee1-d399-4b13-a72a-f24458d590a9
### Get all note threads
GET {{host}}/threads
Accept: application/json

### Get a single note thread
GET {{host}}/threads/{{newThreadId}}
Accept: application/json

### Create a note thread (PUT)
PUT {{host}}/threads/{{newThreadId}}
Content-Type: application/json

{
  "title": "Przykładowy wątek",
  "importance": "HIGH"
}

### Update a note thread (PATCH)
PATCH {{host}}/threads/{{threadId}}
Content-Type: application/json

{
  "title": "Zaktualizowany tytuł"
}

### Delete a note thread
DELETE {{host}}/threads/{{threadId}}


### Get all notes
GET {{host}}/notes
Accept: application/json

### Get notes for a specific thread
GET {{host}}/threads/{{threadId}}/notes
Accept: application/json

### Get a single note
GET {{host}}/notes/{{newNoteId}}
Accept: application/json

### Create a note in a thread (PUT)
PUT {{host}}/threads/{{newThreadId}}/notes/{{newNoteId}}
Content-Type: application/json

{
  "title": "Nowy tytuł notatki",
  "content": "Treść notatki"
}

### Patch a note in a thread (PATCH)
PATCH {{host}}/threads/{{newThreadId}}/notes/{{newNoteId}}
Content-Type: application/json

{
  "content": "Zmieniona treść"
}

### Delete a note
DELETE {{host}}/notes/{{newNoteId}}
